DefaultContentLanguage = "en"
PaginatePath = "page"
baseURL = "https://kaliriu.com"
sectionPagesMenu = "main"
[build]
command = "hugo --gc --minify"
publish = "public"
[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"
[context.branch-deploy.environment]
HUGO_VERSION = "0.96.0"
[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"
[context.deploy-preview.environment]
HUGO_VERSION = "0.96.0"
[context.next.environment]
HUGO_ENABLEGITINFO = "true"
[context.production.environment]
HUGO_ENABLEGITINFO = "true"
HUGO_ENV = "production"
HUGO_VERSION = "0.81.0"
[context.split1]
command = "hugo --gc --minify --enableGitInfo"
[context.split1.environment]
HUGO_ENV = "production"
HUGO_VERSION = "0.81.0"
[languages.en]
contentDir = "content/english"
description = "Kaliriu in English"
languageName = "English"
weight = 1
[[languages.en.menu.main]]
name = "Home"
url = "/en/"
weight = 0
[[languages.en.menu.main]]
name = "Services"
url = "/en/services"
weight = 1
[[languages.en.menu.main]]
name = "Contact"
url = "/en/contact"
weight = 2
[languages.es]
contentDir = "content/spanish"
description = "Kaliriu en Español"
languageName = "Español"
weight = 0
[[languages.es.menu.main]]
name = "Inicio"
url = "/es"
weight = 0
[[languages.es.menu.main]]
name = "Servicios"
url = "/es/servicios"
weight = 1
[[languages.es.menu.main]]
name = "Contacto"
url = "/es/contacto"
weight = 2
[[redirects]]
defaultContentLanguage = "en"
from = "/npmjs/*"
status = 200
to = "/npmjs/"
