baseURL = "https://kaliriu.com/"
title = "Kaliriu"
theme = "kaliriu-theme"


[languages.en]
contentDir = 'content/english'
description = 'Kaliriu in English'
languageCode = 'en-US'
languageName = 'English'
weight = 10

[[languages.en.menu.main]]
identifier = 'home'
name = 'Home'
pageRef = '/'
weight = 1

[[languages.en.menu.main]]
identifier = 'projects'
name = 'Projects'
url = "/projects"
weight = 2

[[languages.en.menu.main]]
identifier = 'blog'
name = 'Blog'
url = "/blog"
weight = 3

[[languages.en.menu.main]]
identifier = 'contact'
name = 'Contact'
url = "/contact"
weight = 4

[languages.es]
contentDir = 'content/spanish'
description = 'Kaliriu en Español'
languageCode = 'es-ES'
languageName = 'Español'
weight = 0

[[languages.es.menu.main]]
identifier = 'inicio'
name = 'Inicio'
pageRef = '/'
weight = 1

[[languages.es.menu.main]]
identifier = 'proyectos'
name = 'Proyectos'
url = "/es/projects"
weight = 2

[[languages.es.menu.main]]
identifier = 'blog'
name = 'Blog'
url = "/es/blog"
weight = 3

[[languages.es.menu.main]]
identifier = 'contacto'
name = 'Contacto'
url = "/es/contact"
weight = 4

