baseURL = 'https://kaliriu.com/'
title = 'Kaliriu'

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true

[languages.en]
contentDir = 'content/english'
description = 'Kaliriu in English'
languageCode = 'en-US'
languageName = 'English'
weight = 1

[[languages.en.menu.main]]
name = 'Home'
pageRef = '/'
weight = 1

[[languages.en.menu.main]]
name = 'Services'
url = "/en/services"
pageRef = 'services'
weight = 2

[[languages.en.menu.main]]
name = 'Contact'
url = "/en/contact"
pageRef = 'contact'
weight = 3

[[languages.en.menu.main]]
name = 'Blog'
url = "/en/blog"
pageRef = 'blog'
weight = 4

[languages.es]
contentDir = 'content/spanish'
description = 'Kaliriu en Español'
languageCode = 'es-ES'
languageName = 'Español'
weight = 2

[[languages.es.menu.main]]
name = 'Inicio'
pageRef = '/'
weight = 1

[[languages.es.menu.main]]
name = 'Servicios'
url = "/es/servicios"
pageRef = 'services'
weight = 1

[[languages.es.menu.main]]
name = 'Contacto'
url = "/es/contacto"
pageRef = 'contact'
weight = 2

[[languages.es.menu.main]]
name = 'Blog'
url = "/es/blog"
pageRef = 'blog'
weight = 3