baseURL = "https://kaliriu.com/"
title = "Kaliriu"
theme = "kaliriu-theme"
metaDataFormat = "yaml"

[build]
command = "hugo --gc --minify"
publish = "public"
[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"
[context.branch-deploy.environment]
HUGO_VERSION = "0.96.0"
[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"
[context.deploy-preview.environment]
HUGO_VERSION = "0.96.0"
[context.next.environment]
HUGO_ENABLEGITINFO = "true"
[context.production.environment]
HUGO_ENABLEGITINFO = "true"
HUGO_ENV = "production"
HUGO_VERSION = "0.81.0"
[context.split1]
command = "hugo --gc --minify --enableGitInfo"
[context.split1.environment]
HUGO_ENV = "production"
HUGO_VERSION = "0.81.0"

defaultContentLanguage = 'en'
[languages]
  [languages.es]
    languageName = 'Spanish'
    weight = 10
    [languages.es.menu]
[[languages.es.menu.main]]
        name = 'Inicio'
        url = '/'
        weight = 0
[[languages.es.menu.main]]
        name = 'Proyectos'
        url = "/es/projects"
        weight = 1
[[languages.es.menu.main]]
        name = 'Blog'
        url = "/es/blog"
        weight = 2
[[languages.es.menu.main]]
        name = 'Contacto'
        url = "/es/contact"
        weight = 3
  [languages.en]
    languageName = 'English'
    weight = 0
    [languages.en.menu]
[[languages.en.menu.main]]
        name = 'Home'
        url = '/'
        weight = 0
[[languages.en.menu.main]]
        name = 'Projects'
        url = "/projects"
        weight = 2
[[languages.en.menu.main]]
        name = 'Blog'
        url = "/blog"
        weight = 3
[[languages.en.menu.main]]
        name = 'Contact'
        url = "/contact"
        weight = 4

