DefaultContentLanguage = "en"
PaginatePath = "page"
baseURL = "https://kaliriu.com"

[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.81.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.81.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.81.0"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.81.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
from = "/npmjs/*"
to = "/npmjs/"
status = 200

[menu]
  [[menu.en]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.en]]
    identifier = "blog"
    name = "Blog"
    url = "/blog"
    weight = 20
  [[menu.en]]
    identifier = "contact"
    name = "Contact"
    url = "/contact"
    weight = 30