baseURL = "https://kaliriu.com"
title = "Kaliriu"
theme = "kaliriu-theme"

[build]
command = "hugo --gc --minify"
publish = "public"
[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"
[context.branch-deploy.environment]
HUGO_VERSION = "0.96.0"
[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"
[context.deploy-preview.environment]
HUGO_VERSION = "0.96.0"
[context.next.environment]
HUGO_ENABLEGITINFO = "true"
[context.production.environment]
HUGO_ENABLEGITINFO = "true"
HUGO_ENV = "production"
HUGO_VERSION = "0.81.0"
[context.split1]
command = "hugo --gc --minify --enableGitInfo"
[context.split1.environment]
HUGO_ENV = "production"
HUGO_VERSION = "0.81.0"

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true

[languages.en]
contentDir = 'content/english'
description = 'Kaliriu in English'
languageCode = 'en-US'
languageName = 'English'
weight = 1

[[languages.en.menu.main]]
name = 'Home'
pageRef = '/'
weight = 1

[[languages.en.menu.main]]
name = 'Projects'
url = "/projects"
pageRef = 'projects'
weight = 2

[[languages.en.menu.main]]
name = 'Blog'
url = "/blog"
weight = 3

[[languages.en.menu.main]]
name = 'Contact'
url = "/contact"
pageRef = 'contact'
weight = 4

[languages.es]
contentDir = 'content/spanish'
description = 'Kaliriu en Español'
languageCode = 'es-ES'
languageName = 'Español'
weight = 2

[[languages.es.menu.main]]
name = 'Inicio'
pageRef = '/'
weight = 1

[[languages.es.menu.main]]
name = 'Projects'
url = "/es/proyectos"
pageRef = 'proyectos'
weight = 1

[[languages.es.menu.main]]
name = 'Blog'
url = "/es/blog"
weight = 2

[[languages.es.menu.main]]
name = 'Contacto'
url = "/es/contacto"
pageRef = 'contact'
weight = 3