---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: 
sections:
- type: heading
  label: ENGLISH
- type: directory
  path: content
  label: Sections
  create: documents
  match: "**"
- type: directory
  path: content/blog
  label: Posts
  create: documents
  match: "**/*"
  exclude: _index.html
  templates:
  - blog
upload_dir: ''
public_path: https://res.cloudinary.com/ddtcgm4kc/image/upload
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.76.5
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.76.5
