---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: 
sections:
- type: heading
  label: ENGLISH
- type: document
  path: content/english/_index.md
  label: Homepage
- type: document
  path: content/english/projects.md
  label: Projects
- type: document
  path: content/english/about.md
  label: About
- type: document
  path: content/english/contact.md
  label: Contact
- type: document
  path: content/english/blog/_index.html
  label: Blog
- type: directory
  path: content/english/blog
  label: Posts
  create: documents
  match: "**/*"
  exclude: _index.html
  templates:
  - blog-post
- type: directory
  path: data/en
  label: Modules
  create: documents
  match: "**/*"
  new_doc_ext: yml
  templates:
  - module-cta
  - module-footer
- type: directory
  path: content/english/legal
  label: Legal
  create: documents
  match: "**/*"
  exclude: _index.html
  templates:
  - legal-post
- type: document
  path: i18n/en.yaml
  label: String ID
- type: heading
  label: SPANISH
- type: document
  path: content/spanish/_index.md
  label: Inicio
- type: document
  path: content/spanish/projects.md
  label: Proyectos
- type: document
  path: content/spanish/about.md
  label: Sobre nosotros
- type: document
  path: content/spanish/contact.md
  label: Contacto
- type: document
  path: content/spanish/blog/_index.html
  label: Blog
- type: directory
  path: content/spanish/blog
  label: Posts
  create: documents
  match: "**/*"
  exclude: _index.html
  templates:
  - blog-post
- type: directory
  path: data/es
  label: Módulos
  create: documents
  match: "**/*"
  new_doc_ext: yml
  templates:
  - module-cta
  - module-footer
- type: directory
  path: content/spanish/legal
  label: Legal
  create: documents
  match: "**/*"
  exclude: _index.html
  templates:
  - legal-post
- type: document
  path: i18n/es.yaml
  label: Hilo ID
upload_dir: ''
public_path: ''
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.81.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.81.0
