---
label: Config
hide_body: true
fields:
- type: text
  name: DefaultContentLanguage
  label: DefaultContentLanguage
  hidden: true
- type: text
  name: baseURL
  label: baseURL
- type: boolean
  name: defaultContentLanguageInSubdir
  label: defaultContentLanguageInSubdir
  hidden: true
- type: list
  name: disableKinds
  label: disableKinds
  hidden: true
- type: text
  name: disqusShortname
  label: disqusShortname
- type: text
  name: metaDataFormat
  label: metaDataFormat
  hidden: true
- type: boolean
  name: pluralizeListTitles
  label: pluralizeListTitles
  hidden: true
- type: text
  name: title
  label: title
- name: Paginate
  type: number
  description: Number of posts displayed in the blog index
  default: '5'
  required: true
  config:
    min: '2'
    max: 
    step: 
    required: true
  label: Blog Index Items
- type: field_group
  name: params
  fields:
  - name: assetsURL
    type: text
    config:
      required: false
    label: Assets URL
    description: Cloudinary URL from where the assets are served. Used for icons and
      background images in the stylesheet.
  - type: file
    name: logo
    label: logo
  label: Logo and Backgrounds
- type: field_group
  name: languages
  label: languages
  fields:
  - type: field_group
    name: en
    label: en
    fields:
    - type: text
      name: contentDir
      label: contentDir
    - type: text
      name: description
      label: description
    - type: text
      name: languageName
      label: languageName
    - type: number
      name: weight
      label: weight
  - type: field_group
    name: es
    label: es
    fields:
    - type: text
      name: contentDir
      label: contentDir
    - type: text
      name: description
      label: description
    - type: text
      name: languageName
      label: languageName
    - type: number
      name: weight
      label: weight
  hidden: true
